name: jiyi
description: "记易, 让记账更容易."
publish_to: 'none' 
version: 0.0.34+0.0.1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  archive: ^3.6.0
  clipboard: ^2.0.2
  http: ^1.5.0
  characters: ^1.4.0
  excel: ^4.0.6
  file_picker: ^10.3.3
  crypto: ^3.0.6
  flutter_gbk2utf8: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/icon/1024.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/1024.png"
  adaptive_icon_monochrome: "assets/icon/1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/1024.png"
